// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vd3_vgg_like_top.h for the primary calling header

#ifndef VERILATED_VD3_VGG_LIKE_TOP___024ROOT_H_
#define VERILATED_VD3_VGG_LIKE_TOP___024ROOT_H_  // guard

#include "verilated.h"


class Vd3_vgg_like_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vd3_vgg_like_top___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(start,0,0);
        VL_IN8(input_we,0,0);
        VL_IN8(input_data,7,0);
        VL_OUT8(busy,0,0);
        VL_OUT8(done,0,0);
        VL_OUT8(class_id,3,0);
        VL_OUT8(argmax_valid,0,0);
        VL_OUT8(state_dbg,3,0);
        CData/*0:0*/ d3_vgg_like_top__DOT__c1_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__c2_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__p1_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__c3_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__c4_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__p2_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__c5_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__gap_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__fc_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__p1_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__p2_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__gap_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__fc_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__p1_busy;
        CData/*0:0*/ d3_vgg_like_top__DOT__p2_busy;
        CData/*0:0*/ d3_vgg_like_top__DOT__gap_busy;
        CData/*0:0*/ d3_vgg_like_top__DOT__fc_busy;
        CData/*7:0*/ d3_vgg_like_top__DOT__a_rd;
        CData/*7:0*/ d3_vgg_like_top__DOT__b_rd;
        CData/*0:0*/ d3_vgg_like_top__DOT__p1_owe;
        CData/*0:0*/ d3_vgg_like_top__DOT__p2_owe;
        CData/*7:0*/ d3_vgg_like_top__DOT__p1_od;
        CData/*7:0*/ d3_vgg_like_top__DOT__p2_od;
        CData/*0:0*/ d3_vgg_like_top__DOT__gap_owe;
        CData/*7:0*/ d3_vgg_like_top__DOT__gap_od;
        CData/*3:0*/ d3_vgg_like_top__DOT__logit_index;
        CData/*0:0*/ d3_vgg_like_top__DOT__logit_valid;
        CData/*7:0*/ d3_vgg_like_top__DOT__c1_wd;
        CData/*7:0*/ d3_vgg_like_top__DOT__c2_wd;
        CData/*7:0*/ d3_vgg_like_top__DOT__c3_wd;
        CData/*7:0*/ d3_vgg_like_top__DOT__c4_wd;
        CData/*7:0*/ d3_vgg_like_top__DOT__c5_wd;
        CData/*7:0*/ d3_vgg_like_top__DOT__fc_wd;
        CData/*3:0*/ d3_vgg_like_top__DOT__fsm__DOT__state;
        CData/*7:0*/ d3_vgg_like_top__DOT__rw4__DOT____Vlvbound_h3992025e__0;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__controller_busy;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__controller_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__postprocess_pending;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__product_valid;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__postprocess_valid;
        CData/*7:0*/ d3_vgg_like_top__DOT__conv1__DOT__out_data_reg;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__controller_done_d1;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__controller_done_d2;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv1__DOT__controller__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__kr;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__kc;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__valid_pixel;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__product_valid;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__product_last;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__last_item;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine_start;
    };
    struct {
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__controller_busy;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__controller_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__postprocess_pending;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__product_valid;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__postprocess_valid;
        CData/*7:0*/ d3_vgg_like_top__DOT__conv2__DOT__out_data_reg;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__controller_done_d1;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__controller_done_d2;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv2__DOT__controller__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__kr;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__kc;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__valid_pixel;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__product_valid;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__product_last;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__last_item;
        CData/*2:0*/ d3_vgg_like_top__DOT__pool1__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__pool1__DOT__tap;
        CData/*7:0*/ d3_vgg_like_top__DOT__pool1__DOT__current_max;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__controller_busy;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__controller_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__postprocess_pending;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__product_valid;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__postprocess_valid;
        CData/*7:0*/ d3_vgg_like_top__DOT__conv3__DOT__out_data_reg;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__controller_done_d1;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__controller_done_d2;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv3__DOT__controller__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__kr;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__kc;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__valid_pixel;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__product_valid;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__product_last;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__last_item;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__controller_busy;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__controller_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__postprocess_pending;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__product_valid;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__postprocess_valid;
        CData/*7:0*/ d3_vgg_like_top__DOT__conv4__DOT__out_data_reg;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__controller_done_d1;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__controller_done_d2;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv4__DOT__controller__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__kr;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__kc;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__valid_pixel;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__product_valid;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__product_last;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__last_item;
        CData/*2:0*/ d3_vgg_like_top__DOT__pool2__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__pool2__DOT__tap;
        CData/*7:0*/ d3_vgg_like_top__DOT__pool2__DOT__current_max;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine_start;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__controller_busy;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__controller_done;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__postprocess_pending;
    };
    struct {
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__product_valid;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__postprocess_valid;
        CData/*7:0*/ d3_vgg_like_top__DOT__conv5__DOT__out_data_reg;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__controller_done_d1;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__controller_done_d2;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv5__DOT__controller__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__state;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__kr;
        CData/*1:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__kc;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__valid_pixel;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__product_valid;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__product_last;
        CData/*0:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__last_item;
        CData/*2:0*/ d3_vgg_like_top__DOT__gap__DOT__state;
        CData/*2:0*/ d3_vgg_like_top__DOT__linear__DOT__state;
        CData/*3:0*/ d3_vgg_like_top__DOT__linear__DOT__class_idx;
        CData/*6:0*/ d3_vgg_like_top__DOT__linear__DOT__feature_idx;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_0;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__c1_start;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__c2_start;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__p1_start;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__c3_start;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__c4_start;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__p2_start;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__c5_start;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__gap_start;
        CData/*3:0*/ __Vdly__state_dbg;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv1__DOT__engine_start;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__conv1__DOT__controller__DOT__state;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__state;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__product_valid;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__product_last;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv2__DOT__engine_start;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__conv2__DOT__controller__DOT__state;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__state;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__product_valid;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__product_last;
        CData/*2:0*/ __Vdly__d3_vgg_like_top__DOT__pool1__DOT__state;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__pool1__DOT__tap;
        CData/*7:0*/ __Vdly__d3_vgg_like_top__DOT__pool1__DOT__current_max;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv3__DOT__engine_start;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__conv3__DOT__controller__DOT__state;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__state;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__product_valid;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__product_last;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv4__DOT__engine_start;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__conv4__DOT__controller__DOT__state;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__state;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__product_valid;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__product_last;
        CData/*2:0*/ __Vdly__d3_vgg_like_top__DOT__pool2__DOT__state;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__pool2__DOT__tap;
        CData/*7:0*/ __Vdly__d3_vgg_like_top__DOT__pool2__DOT__current_max;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv5__DOT__engine_start;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__conv5__DOT__controller__DOT__state;
        CData/*1:0*/ __Vdly__d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__state;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__product_valid;
        CData/*0:0*/ __Vdly__d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__product_last;
        CData/*2:0*/ __Vdly__d3_vgg_like_top__DOT__gap__DOT__state;
        CData/*6:0*/ __Vdly__d3_vgg_like_top__DOT__linear__DOT__feature_idx;
        CData/*7:0*/ __VdlyVal__d3_vgg_like_top__DOT__buffer_a__DOT__mem__v0;
        CData/*0:0*/ __VdlySet__d3_vgg_like_top__DOT__buffer_a__DOT__mem__v0;
        CData/*7:0*/ __VdlyVal__d3_vgg_like_top__DOT__buffer_b__DOT__mem__v0;
        CData/*0:0*/ __VdlySet__d3_vgg_like_top__DOT__buffer_b__DOT__mem__v0;
    };
    struct {
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*9:0*/ d3_vgg_like_top__DOT__rw1__DOT__rom_addr;
        SData/*13:0*/ d3_vgg_like_top__DOT__rw2__DOT__rom_addr;
        SData/*14:0*/ d3_vgg_like_top__DOT__rw3__DOT__rom_addr;
        SData/*10:0*/ d3_vgg_like_top__DOT__rwf__DOT__rom_addr;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv1__DOT__out_row;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv1__DOT__out_col;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv1__DOT__out_channel;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__ic;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__product_reg;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv2__DOT__out_row;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv2__DOT__out_col;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv2__DOT__out_channel;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__ic;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__product_reg;
        SData/*15:0*/ d3_vgg_like_top__DOT__pool1__DOT__ch;
        SData/*15:0*/ d3_vgg_like_top__DOT__pool1__DOT__row;
        SData/*15:0*/ d3_vgg_like_top__DOT__pool1__DOT__col;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv3__DOT__out_row;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv3__DOT__out_col;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv3__DOT__out_channel;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__ic;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__product_reg;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv4__DOT__out_row;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv4__DOT__out_col;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv4__DOT__out_channel;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__ic;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__product_reg;
        SData/*15:0*/ d3_vgg_like_top__DOT__pool2__DOT__ch;
        SData/*15:0*/ d3_vgg_like_top__DOT__pool2__DOT__row;
        SData/*15:0*/ d3_vgg_like_top__DOT__pool2__DOT__col;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv5__DOT__out_row;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv5__DOT__out_col;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv5__DOT__out_channel;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__ic;
        SData/*15:0*/ d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__product_reg;
        SData/*15:0*/ d3_vgg_like_top__DOT__gap__DOT__ch;
        SData/*15:0*/ d3_vgg_like_top__DOT__gap__DOT__idx;
        SData/*14:0*/ __VdfgRegularize_h6e95ff9d_0_14;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__ic;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__conv1__DOT__engine__DOT__product_reg;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__ic;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__conv2__DOT__engine__DOT__product_reg;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__ic;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__conv3__DOT__engine__DOT__product_reg;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__ic;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__conv4__DOT__engine__DOT__product_reg;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__pool2__DOT__col;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__pool2__DOT__row;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__pool2__DOT__ch;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__ic;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__conv5__DOT__engine__DOT__product_reg;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__gap__DOT__idx;
        SData/*15:0*/ __Vdly__d3_vgg_like_top__DOT__gap__DOT__ch;
        SData/*14:0*/ __VdlyDim0__d3_vgg_like_top__DOT__buffer_a__DOT__mem__v0;
        SData/*14:0*/ __VdlyDim0__d3_vgg_like_top__DOT__buffer_b__DOT__mem__v0;
        VL_IN(input_addr,16,0);
    };
    struct {
        VL_OUT(max_logit,31,0);
        IData/*16:0*/ d3_vgg_like_top__DOT__c4_wa;
        IData/*16:0*/ d3_vgg_like_top__DOT__c5_wa;
        IData/*16:0*/ d3_vgg_like_top__DOT__p1_oa;
        IData/*16:0*/ d3_vgg_like_top__DOT__p2_oa;
        IData/*16:0*/ d3_vgg_like_top__DOT__gap_oa;
        IData/*31:0*/ d3_vgg_like_top__DOT__logit_data;
        IData/*31:0*/ d3_vgg_like_top__DOT__l0;
        IData/*31:0*/ d3_vgg_like_top__DOT__l1;
        IData/*31:0*/ d3_vgg_like_top__DOT__l2;
        IData/*31:0*/ d3_vgg_like_top__DOT__l3;
        IData/*31:0*/ d3_vgg_like_top__DOT__l4;
        IData/*31:0*/ d3_vgg_like_top__DOT__l5;
        IData/*31:0*/ d3_vgg_like_top__DOT__l6;
        IData/*31:0*/ d3_vgg_like_top__DOT__l7;
        IData/*31:0*/ d3_vgg_like_top__DOT__l8;
        IData/*31:0*/ d3_vgg_like_top__DOT__l9;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv1__DOT__raw_sum;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv1__DOT__biased_sum_reg;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv1__DOT__activated;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv1__DOT__controller_out_addr;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv1__DOT__product_addr_reg;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv1__DOT__out_addr_reg;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv2__DOT__raw_sum;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv2__DOT__biased_sum_reg;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv2__DOT__activated;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv2__DOT__controller_out_addr;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv2__DOT__product_addr_reg;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv2__DOT__out_addr_reg;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv3__DOT__raw_sum;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv3__DOT__biased_sum_reg;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv3__DOT__activated;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv3__DOT__controller_out_addr;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv3__DOT__product_addr_reg;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv3__DOT__out_addr_reg;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv4__DOT__raw_sum;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv4__DOT__biased_sum_reg;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv4__DOT__activated;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv4__DOT__controller_out_addr;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv4__DOT__product_addr_reg;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv4__DOT__out_addr_reg;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv5__DOT__raw_sum;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv5__DOT__biased_sum_reg;
        IData/*31:0*/ d3_vgg_like_top__DOT__conv5__DOT__activated;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv5__DOT__controller_out_addr;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv5__DOT__product_addr_reg;
        IData/*16:0*/ d3_vgg_like_top__DOT__conv5__DOT__out_addr_reg;
        IData/*31:0*/ d3_vgg_like_top__DOT__gap__DOT__sum;
        IData/*31:0*/ d3_vgg_like_top__DOT__linear__DOT__acc;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_2;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_3;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_4;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_5;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_6;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_7;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_8;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_9;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_10;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_11;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_13;
        IData/*31:0*/ __Vdly__d3_vgg_like_top__DOT__gap__DOT__sum;
        IData/*31:0*/ __VactIterCount;
        QData/*42:0*/ d3_vgg_like_top__DOT__conv1__DOT__product_reg;
        QData/*42:0*/ d3_vgg_like_top__DOT__conv2__DOT__product_reg;
    };
    struct {
        QData/*42:0*/ d3_vgg_like_top__DOT__conv3__DOT__product_reg;
        QData/*42:0*/ d3_vgg_like_top__DOT__conv4__DOT__product_reg;
        QData/*42:0*/ d3_vgg_like_top__DOT__conv5__DOT__product_reg;
        VlUnpacked<CData/*7:0*/, 32768> d3_vgg_like_top__DOT__buffer_a__DOT__mem;
        VlUnpacked<CData/*7:0*/, 32768> d3_vgg_like_top__DOT__buffer_b__DOT__mem;
        VlUnpacked<CData/*7:0*/, 864> d3_vgg_like_top__DOT__rw1__DOT__rom;
        VlUnpacked<CData/*7:0*/, 9216> d3_vgg_like_top__DOT__rw2__DOT__rom;
        VlUnpacked<CData/*7:0*/, 18432> d3_vgg_like_top__DOT__rw3__DOT__rom;
        VlUnpacked<CData/*7:0*/, 36864> d3_vgg_like_top__DOT__rw4__DOT__rom;
        VlUnpacked<CData/*7:0*/, 73728> d3_vgg_like_top__DOT__rw5__DOT__rom;
        VlUnpacked<CData/*7:0*/, 1280> d3_vgg_like_top__DOT__rwf__DOT__rom;
        VlUnpacked<IData/*31:0*/, 32> d3_vgg_like_top__DOT__rb1__DOT__rom;
        VlUnpacked<IData/*31:0*/, 32> d3_vgg_like_top__DOT__rb2__DOT__rom;
        VlUnpacked<IData/*31:0*/, 64> d3_vgg_like_top__DOT__rb3__DOT__rom;
        VlUnpacked<IData/*31:0*/, 64> d3_vgg_like_top__DOT__rb4__DOT__rom;
        VlUnpacked<IData/*31:0*/, 128> d3_vgg_like_top__DOT__rb5__DOT__rom;
        VlUnpacked<IData/*31:0*/, 10> d3_vgg_like_top__DOT__rbf__DOT__rom;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vd3_vgg_like_top__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vd3_vgg_like_top___024root(Vd3_vgg_like_top__Syms* symsp, const char* namep);
    ~Vd3_vgg_like_top___024root();
    VL_UNCOPYABLE(Vd3_vgg_like_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
