# Generated by per_layer_ptq.py; do not edit manually.
set Q_CONV1_M 47225
set Q_CONV1_S 24
set Q_CONV2_M 42597
set Q_CONV2_S 24
set Q_CONV3_M 57750
set Q_CONV3_S 24
set Q_CONV4_M 73626
set Q_CONV4_S 23
