// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vedge_cnn_top.h for the primary calling header

#ifndef VERILATED_VEDGE_CNN_TOP___024ROOT_H_
#define VERILATED_VEDGE_CNN_TOP___024ROOT_H_  // guard

#include "verilated.h"


class Vedge_cnn_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vedge_cnn_top___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(start,0,0);
        VL_IN8(input_we,0,0);
        VL_IN8(input_data,7,0);
        VL_OUT8(conv1_start,0,0);
        VL_OUT8(pool1_start,0,0);
        VL_OUT8(conv2_start,0,0);
        VL_OUT8(pool2_start,0,0);
        VL_OUT8(conv3_start,0,0);
        VL_OUT8(conv4_start,0,0);
        VL_OUT8(gap_start,0,0);
        VL_OUT8(linear_start,0,0);
        VL_OUT8(argmax_valid,0,0);
        VL_OUT8(busy,0,0);
        VL_OUT8(done,0,0);
        VL_OUT8(class_id,3,0);
        VL_OUT8(state_dbg,3,0);
        CData/*0:0*/ edge_cnn_top__DOT__pool1_done;
        CData/*0:0*/ edge_cnn_top__DOT__pool2_done;
        CData/*0:0*/ edge_cnn_top__DOT__gap_done;
        CData/*0:0*/ edge_cnn_top__DOT__linear_done;
        CData/*0:0*/ edge_cnn_top__DOT__pool1_busy;
        CData/*0:0*/ edge_cnn_top__DOT__pool2_busy;
        CData/*0:0*/ edge_cnn_top__DOT__gap_busy;
        CData/*0:0*/ edge_cnn_top__DOT__linear_busy;
        CData/*7:0*/ edge_cnn_top__DOT__buf_a_rdata;
        CData/*7:0*/ edge_cnn_top__DOT__buf_b_rdata;
        CData/*0:0*/ edge_cnn_top__DOT__pool1_out_we;
        CData/*0:0*/ edge_cnn_top__DOT__pool2_out_we;
        CData/*7:0*/ edge_cnn_top__DOT__pool1_out_data;
        CData/*7:0*/ edge_cnn_top__DOT__pool2_out_data;
        CData/*0:0*/ edge_cnn_top__DOT__gap_out_we;
        CData/*7:0*/ edge_cnn_top__DOT__gap_out_data;
        CData/*3:0*/ edge_cnn_top__DOT__linear_logit_index;
        CData/*0:0*/ edge_cnn_top__DOT__linear_logit_valid;
        CData/*7:0*/ edge_cnn_top__DOT__conv1_weight_data;
        CData/*7:0*/ edge_cnn_top__DOT__conv2_weight_data;
        CData/*7:0*/ edge_cnn_top__DOT__conv3_weight_data;
        CData/*7:0*/ edge_cnn_top__DOT__conv4_weight_data;
        CData/*7:0*/ edge_cnn_top__DOT__linear_weight_data;
        CData/*3:0*/ edge_cnn_top__DOT__fsm__DOT__state;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__engine_start;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__engine_done;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__controller_busy;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__controller_done;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__postprocess_pending;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__product_valid;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__postprocess_valid;
        CData/*7:0*/ edge_cnn_top__DOT__conv1__DOT__out_data_reg;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__controller_done_d1;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__controller_done_d2;
        CData/*1:0*/ edge_cnn_top__DOT__conv1__DOT__controller__DOT__state;
        CData/*1:0*/ edge_cnn_top__DOT__conv1__DOT__engine__DOT__state;
        CData/*1:0*/ edge_cnn_top__DOT__conv1__DOT__engine__DOT__kr;
        CData/*1:0*/ edge_cnn_top__DOT__conv1__DOT__engine__DOT__kc;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__engine__DOT__valid_pixel;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__engine__DOT__product_valid;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__engine__DOT__product_last;
        CData/*0:0*/ edge_cnn_top__DOT__conv1__DOT__engine__DOT__last_item;
        CData/*2:0*/ edge_cnn_top__DOT__pool1__DOT__state;
        CData/*1:0*/ edge_cnn_top__DOT__pool1__DOT__tap;
        CData/*7:0*/ edge_cnn_top__DOT__pool1__DOT__current_max;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__engine_start;
    };
    struct {
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__engine_done;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__controller_busy;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__controller_done;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__postprocess_pending;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__product_valid;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__postprocess_valid;
        CData/*7:0*/ edge_cnn_top__DOT__conv2__DOT__out_data_reg;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__controller_done_d1;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__controller_done_d2;
        CData/*1:0*/ edge_cnn_top__DOT__conv2__DOT__controller__DOT__state;
        CData/*1:0*/ edge_cnn_top__DOT__conv2__DOT__engine__DOT__state;
        CData/*1:0*/ edge_cnn_top__DOT__conv2__DOT__engine__DOT__kr;
        CData/*1:0*/ edge_cnn_top__DOT__conv2__DOT__engine__DOT__kc;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__engine__DOT__valid_pixel;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__engine__DOT__product_valid;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__engine__DOT__product_last;
        CData/*0:0*/ edge_cnn_top__DOT__conv2__DOT__engine__DOT__last_item;
        CData/*2:0*/ edge_cnn_top__DOT__pool2__DOT__state;
        CData/*1:0*/ edge_cnn_top__DOT__pool2__DOT__tap;
        CData/*7:0*/ edge_cnn_top__DOT__pool2__DOT__current_max;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__engine_start;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__engine_done;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__controller_busy;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__controller_done;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__postprocess_pending;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__product_valid;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__postprocess_valid;
        CData/*7:0*/ edge_cnn_top__DOT__conv3__DOT__out_data_reg;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__controller_done_d1;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__controller_done_d2;
        CData/*1:0*/ edge_cnn_top__DOT__conv3__DOT__controller__DOT__state;
        CData/*1:0*/ edge_cnn_top__DOT__conv3__DOT__engine__DOT__state;
        CData/*1:0*/ edge_cnn_top__DOT__conv3__DOT__engine__DOT__kr;
        CData/*1:0*/ edge_cnn_top__DOT__conv3__DOT__engine__DOT__kc;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__engine__DOT__valid_pixel;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__engine__DOT__product_valid;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__engine__DOT__product_last;
        CData/*0:0*/ edge_cnn_top__DOT__conv3__DOT__engine__DOT__last_item;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__engine_start;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__engine_done;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__controller_busy;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__controller_done;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__postprocess_pending;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__product_valid;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__postprocess_valid;
        CData/*7:0*/ edge_cnn_top__DOT__conv4__DOT__out_data_reg;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__controller_done_d1;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__controller_done_d2;
        CData/*1:0*/ edge_cnn_top__DOT__conv4__DOT__controller__DOT__state;
        CData/*1:0*/ edge_cnn_top__DOT__conv4__DOT__engine__DOT__state;
        CData/*1:0*/ edge_cnn_top__DOT__conv4__DOT__engine__DOT__kr;
        CData/*1:0*/ edge_cnn_top__DOT__conv4__DOT__engine__DOT__kc;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__engine__DOT__valid_pixel;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__engine__DOT__product_valid;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__engine__DOT__product_last;
        CData/*0:0*/ edge_cnn_top__DOT__conv4__DOT__engine__DOT__last_item;
        CData/*2:0*/ edge_cnn_top__DOT__gap__DOT__state;
        CData/*2:0*/ edge_cnn_top__DOT__linear__DOT__state;
        CData/*3:0*/ edge_cnn_top__DOT__linear__DOT__class_idx;
        CData/*7:0*/ edge_cnn_top__DOT__linear__DOT__feature_idx;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_0;
        CData/*0:0*/ __Vdly__conv1_start;
        CData/*0:0*/ __Vdly__pool1_start;
        CData/*0:0*/ __Vdly__conv2_start;
    };
    struct {
        CData/*0:0*/ __Vdly__pool2_start;
        CData/*0:0*/ __Vdly__conv3_start;
        CData/*0:0*/ __Vdly__conv4_start;
        CData/*0:0*/ __Vdly__gap_start;
        CData/*3:0*/ __Vdly__state_dbg;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv1__DOT__engine_start;
        CData/*1:0*/ __Vdly__edge_cnn_top__DOT__conv1__DOT__controller__DOT__state;
        CData/*1:0*/ __Vdly__edge_cnn_top__DOT__conv1__DOT__engine__DOT__state;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv1__DOT__engine__DOT__product_valid;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv1__DOT__engine__DOT__product_last;
        CData/*2:0*/ __Vdly__edge_cnn_top__DOT__pool1__DOT__state;
        CData/*1:0*/ __Vdly__edge_cnn_top__DOT__pool1__DOT__tap;
        CData/*7:0*/ __Vdly__edge_cnn_top__DOT__pool1__DOT__current_max;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv2__DOT__engine_start;
        CData/*1:0*/ __Vdly__edge_cnn_top__DOT__conv2__DOT__controller__DOT__state;
        CData/*1:0*/ __Vdly__edge_cnn_top__DOT__conv2__DOT__engine__DOT__state;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv2__DOT__engine__DOT__product_valid;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv2__DOT__engine__DOT__product_last;
        CData/*2:0*/ __Vdly__edge_cnn_top__DOT__pool2__DOT__state;
        CData/*1:0*/ __Vdly__edge_cnn_top__DOT__pool2__DOT__tap;
        CData/*7:0*/ __Vdly__edge_cnn_top__DOT__pool2__DOT__current_max;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv3__DOT__engine_start;
        CData/*1:0*/ __Vdly__edge_cnn_top__DOT__conv3__DOT__controller__DOT__state;
        CData/*1:0*/ __Vdly__edge_cnn_top__DOT__conv3__DOT__engine__DOT__state;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv3__DOT__engine__DOT__product_valid;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv3__DOT__engine__DOT__product_last;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv4__DOT__engine_start;
        CData/*1:0*/ __Vdly__edge_cnn_top__DOT__conv4__DOT__controller__DOT__state;
        CData/*1:0*/ __Vdly__edge_cnn_top__DOT__conv4__DOT__engine__DOT__state;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv4__DOT__engine__DOT__product_valid;
        CData/*0:0*/ __Vdly__edge_cnn_top__DOT__conv4__DOT__engine__DOT__product_last;
        CData/*2:0*/ __Vdly__edge_cnn_top__DOT__gap__DOT__state;
        CData/*7:0*/ __Vdly__edge_cnn_top__DOT__linear__DOT__feature_idx;
        CData/*7:0*/ __VdlyVal__edge_cnn_top__DOT__buffer_a__DOT__mem__v0;
        CData/*0:0*/ __VdlySet__edge_cnn_top__DOT__buffer_a__DOT__mem__v0;
        CData/*7:0*/ __VdlyVal__edge_cnn_top__DOT__buffer_b__DOT__mem__v0;
        CData/*0:0*/ __VdlySet__edge_cnn_top__DOT__buffer_b__DOT__mem__v0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*9:0*/ edge_cnn_top__DOT__conv1_weight_rom__DOT__rom_addr;
        SData/*14:0*/ edge_cnn_top__DOT__conv2_weight_rom__DOT__rom_addr;
        SData/*11:0*/ edge_cnn_top__DOT__linear_weight_rom__DOT__rom_addr;
        SData/*15:0*/ edge_cnn_top__DOT__conv1__DOT__out_row;
        SData/*15:0*/ edge_cnn_top__DOT__conv1__DOT__out_col;
        SData/*15:0*/ edge_cnn_top__DOT__conv1__DOT__out_channel;
        SData/*15:0*/ edge_cnn_top__DOT__conv1__DOT__engine__DOT__ic;
        SData/*15:0*/ edge_cnn_top__DOT__conv1__DOT__engine__DOT__product_reg;
        SData/*15:0*/ edge_cnn_top__DOT__pool1__DOT__ch;
        SData/*15:0*/ edge_cnn_top__DOT__pool1__DOT__row;
        SData/*15:0*/ edge_cnn_top__DOT__pool1__DOT__col;
        SData/*15:0*/ edge_cnn_top__DOT__conv2__DOT__out_row;
        SData/*15:0*/ edge_cnn_top__DOT__conv2__DOT__out_col;
        SData/*15:0*/ edge_cnn_top__DOT__conv2__DOT__out_channel;
        SData/*15:0*/ edge_cnn_top__DOT__conv2__DOT__engine__DOT__ic;
        SData/*15:0*/ edge_cnn_top__DOT__conv2__DOT__engine__DOT__product_reg;
        SData/*15:0*/ edge_cnn_top__DOT__pool2__DOT__ch;
        SData/*15:0*/ edge_cnn_top__DOT__pool2__DOT__row;
        SData/*15:0*/ edge_cnn_top__DOT__pool2__DOT__col;
    };
    struct {
        SData/*15:0*/ edge_cnn_top__DOT__conv3__DOT__out_row;
        SData/*15:0*/ edge_cnn_top__DOT__conv3__DOT__out_col;
        SData/*15:0*/ edge_cnn_top__DOT__conv3__DOT__out_channel;
        SData/*15:0*/ edge_cnn_top__DOT__conv3__DOT__engine__DOT__ic;
        SData/*15:0*/ edge_cnn_top__DOT__conv3__DOT__engine__DOT__product_reg;
        SData/*15:0*/ edge_cnn_top__DOT__conv4__DOT__out_row;
        SData/*15:0*/ edge_cnn_top__DOT__conv4__DOT__out_col;
        SData/*15:0*/ edge_cnn_top__DOT__conv4__DOT__out_channel;
        SData/*15:0*/ edge_cnn_top__DOT__conv4__DOT__engine__DOT__ic;
        SData/*15:0*/ edge_cnn_top__DOT__conv4__DOT__engine__DOT__product_reg;
        SData/*15:0*/ edge_cnn_top__DOT__gap__DOT__ch;
        SData/*15:0*/ edge_cnn_top__DOT__gap__DOT__idx;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__conv1__DOT__engine__DOT__ic;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__conv1__DOT__engine__DOT__product_reg;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__pool1__DOT__col;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__pool1__DOT__row;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__pool1__DOT__ch;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__conv2__DOT__engine__DOT__ic;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__conv2__DOT__engine__DOT__product_reg;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__pool2__DOT__col;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__pool2__DOT__row;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__pool2__DOT__ch;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__conv3__DOT__engine__DOT__ic;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__conv3__DOT__engine__DOT__product_reg;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__conv4__DOT__engine__DOT__ic;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__conv4__DOT__engine__DOT__product_reg;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__gap__DOT__idx;
        SData/*15:0*/ __Vdly__edge_cnn_top__DOT__gap__DOT__ch;
        SData/*14:0*/ __VdlyDim0__edge_cnn_top__DOT__buffer_a__DOT__mem__v0;
        SData/*14:0*/ __VdlyDim0__edge_cnn_top__DOT__buffer_b__DOT__mem__v0;
        VL_IN(input_addr,18,0);
        VL_OUT(max_logit,31,0);
        IData/*18:0*/ edge_cnn_top__DOT__conv4_weight_addr;
        IData/*18:0*/ edge_cnn_top__DOT__pool1_out_addr;
        IData/*18:0*/ edge_cnn_top__DOT__pool2_out_addr;
        IData/*18:0*/ edge_cnn_top__DOT__gap_out_addr;
        IData/*31:0*/ edge_cnn_top__DOT__linear_logit_data;
        IData/*31:0*/ edge_cnn_top__DOT__logit0;
        IData/*31:0*/ edge_cnn_top__DOT__logit1;
        IData/*31:0*/ edge_cnn_top__DOT__logit2;
        IData/*31:0*/ edge_cnn_top__DOT__logit3;
        IData/*31:0*/ edge_cnn_top__DOT__logit4;
        IData/*31:0*/ edge_cnn_top__DOT__logit5;
        IData/*31:0*/ edge_cnn_top__DOT__logit6;
        IData/*31:0*/ edge_cnn_top__DOT__logit7;
        IData/*31:0*/ edge_cnn_top__DOT__logit8;
        IData/*31:0*/ edge_cnn_top__DOT__logit9;
        IData/*16:0*/ edge_cnn_top__DOT__conv3_weight_rom__DOT__rom_addr;
        IData/*31:0*/ edge_cnn_top__DOT__conv1__DOT__raw_sum;
        IData/*31:0*/ edge_cnn_top__DOT__conv1__DOT__biased_sum_reg;
        IData/*31:0*/ edge_cnn_top__DOT__conv1__DOT__activated;
        IData/*18:0*/ edge_cnn_top__DOT__conv1__DOT__controller_out_addr;
        IData/*18:0*/ edge_cnn_top__DOT__conv1__DOT__product_addr_reg;
        IData/*18:0*/ edge_cnn_top__DOT__conv1__DOT__out_addr_reg;
        IData/*31:0*/ edge_cnn_top__DOT__conv2__DOT__raw_sum;
        IData/*31:0*/ edge_cnn_top__DOT__conv2__DOT__biased_sum_reg;
        IData/*31:0*/ edge_cnn_top__DOT__conv2__DOT__activated;
        IData/*18:0*/ edge_cnn_top__DOT__conv2__DOT__controller_out_addr;
        IData/*18:0*/ edge_cnn_top__DOT__conv2__DOT__product_addr_reg;
        IData/*18:0*/ edge_cnn_top__DOT__conv2__DOT__out_addr_reg;
        IData/*31:0*/ edge_cnn_top__DOT__conv3__DOT__raw_sum;
        IData/*31:0*/ edge_cnn_top__DOT__conv3__DOT__biased_sum_reg;
        IData/*31:0*/ edge_cnn_top__DOT__conv3__DOT__activated;
        IData/*18:0*/ edge_cnn_top__DOT__conv3__DOT__controller_out_addr;
    };
    struct {
        IData/*18:0*/ edge_cnn_top__DOT__conv3__DOT__product_addr_reg;
        IData/*18:0*/ edge_cnn_top__DOT__conv3__DOT__out_addr_reg;
        IData/*31:0*/ edge_cnn_top__DOT__conv4__DOT__raw_sum;
        IData/*31:0*/ edge_cnn_top__DOT__conv4__DOT__biased_sum_reg;
        IData/*31:0*/ edge_cnn_top__DOT__conv4__DOT__activated;
        IData/*18:0*/ edge_cnn_top__DOT__conv4__DOT__controller_out_addr;
        IData/*18:0*/ edge_cnn_top__DOT__conv4__DOT__product_addr_reg;
        IData/*18:0*/ edge_cnn_top__DOT__conv4__DOT__out_addr_reg;
        IData/*31:0*/ edge_cnn_top__DOT__gap__DOT__sum;
        IData/*31:0*/ edge_cnn_top__DOT__linear__DOT__acc;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_2;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_3;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_4;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_5;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_6;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_7;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_8;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_9;
        IData/*31:0*/ __VdfgRegularize_h6e95ff9d_0_10;
        IData/*31:0*/ __Vdly__edge_cnn_top__DOT__gap__DOT__sum;
        IData/*31:0*/ __VactIterCount;
        QData/*42:0*/ edge_cnn_top__DOT__conv1__DOT__product_reg;
        QData/*42:0*/ edge_cnn_top__DOT__conv2__DOT__product_reg;
        QData/*42:0*/ edge_cnn_top__DOT__conv3__DOT__product_reg;
        QData/*42:0*/ edge_cnn_top__DOT__conv4__DOT__product_reg;
        VlUnpacked<CData/*7:0*/, 32768> edge_cnn_top__DOT__buffer_a__DOT__mem;
        VlUnpacked<CData/*7:0*/, 32768> edge_cnn_top__DOT__buffer_b__DOT__mem;
        VlUnpacked<CData/*7:0*/, 864> edge_cnn_top__DOT__conv1_weight_rom__DOT__rom;
        VlUnpacked<CData/*7:0*/, 18432> edge_cnn_top__DOT__conv2_weight_rom__DOT__rom;
        VlUnpacked<CData/*7:0*/, 73728> edge_cnn_top__DOT__conv3_weight_rom__DOT__rom;
        VlUnpacked<CData/*7:0*/, 294912> edge_cnn_top__DOT__conv4_weight_rom__DOT__rom;
        VlUnpacked<CData/*7:0*/, 2560> edge_cnn_top__DOT__linear_weight_rom__DOT__rom;
        VlUnpacked<IData/*31:0*/, 32> edge_cnn_top__DOT__conv1_bias_rom__DOT__rom;
        VlUnpacked<IData/*31:0*/, 64> edge_cnn_top__DOT__conv2_bias_rom__DOT__rom;
        VlUnpacked<IData/*31:0*/, 128> edge_cnn_top__DOT__conv3_bias_rom__DOT__rom;
        VlUnpacked<IData/*31:0*/, 256> edge_cnn_top__DOT__conv4_bias_rom__DOT__rom;
        VlUnpacked<IData/*31:0*/, 10> edge_cnn_top__DOT__linear_bias_rom__DOT__rom;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vedge_cnn_top__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vedge_cnn_top___024root(Vedge_cnn_top__Syms* symsp, const char* namep);
    ~Vedge_cnn_top___024root();
    VL_UNCOPYABLE(Vedge_cnn_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
