# Generated by per_layer_ptq.py; do not edit manually.
set Q_CONV1_M 44702
set Q_CONV1_S 24
set Q_CONV2_M 63368
set Q_CONV2_S 24
set Q_CONV3_M 51415
set Q_CONV3_S 24
set Q_CONV4_M 56297
set Q_CONV4_S 24
